from dataclasses import dataclass

@dataclass(frozen=True)
class VenueInfo:
    city: str
    venueName: str

VENUE_INFO_MAP: dict[str, VenueInfo] = {
    "entréplan": VenueInfo(city="Stockholm", venueName="Entréplan, Kulturhuset Stadsteatern"),
    "foajé 4": VenueInfo(city="Stockholm", venueName="Foajé 4, Kulturhuset Stadsteatern"),
    "galleri 3": VenueInfo(city="Stockholm", venueName="Galleri 3, Kulturhuset Stadsteatern"),
    "galleri 5": VenueInfo(city="Stockholm", venueName="Galleri 5, Kulturhuset Stadsteatern"),
    "galleriet vällingby": VenueInfo(city="Vällingby", venueName="Galleriet Vällingby"),
    "galärparken": VenueInfo(city="Stockholm", venueName="Parkteatern Galärparken"),
    "husby": VenueInfo(city="Kista", venueName="Kulturhuset Stadsteatern Husby"),
    "hörsalen": VenueInfo(city="Stockholm", venueName="Hörsalen, Kulturhuset Stadsteatern"),
    "kafé klara": VenueInfo(city="Stockholm", venueName="Kafé Klara, Kulturhuset Stadsteatern"),
    "kilen": VenueInfo(city="Stockholm", venueName="Kilen, Kulturhuset Stadsteatern"),
    "klarabiografen": VenueInfo(city="Stockholm", venueName="Klarabiografen, Kulturhuset Stadsteatern"),
    "klarascenen": VenueInfo(city="Stockholm", venueName="Klarascenen, Kulturhuset Stadsteatern"),
    "kulturbiblioteket": VenueInfo(city="Stockholm", venueName="Kulturbiblioteket, Kulturhuset Stadsteatern"),
    "lava": VenueInfo(city="Stockholm", venueName="Lava, Kulturhuset Stadsteatern"),
    "lilla kilen": VenueInfo(city="Stockholm", venueName="Lilla Kilen, Kulturhuset Stadsteatern"),
    "lilla scenen": VenueInfo(city="Stockholm", venueName="Lilla scenen, Kulturhuset Stadsteatern"),
    "marionetteatern": VenueInfo(city="Stockholm", venueName="Marionetteatern, Kulturhuset Stadsteatern"),
    "sergels torg": VenueInfo(city="Stockholm", venueName="Sergels torg, Kulturhuset Stadsteatern"),
    "skärholmen foajén": VenueInfo(city="Skärholmen", venueName="Skärholmen Foajén"),
    "skärisbiografen": VenueInfo(city="Skärholmen", venueName="Skärisbiografen"),
    "stora scenen skärholmen": VenueInfo(city="Skärholmen", venueName="Stora Scenen Skärholmen"),
    "stora scenen": VenueInfo(city="Stockholm", venueName="Stora scenen, Kulturhuset Stadsteatern"),
    "studion": VenueInfo(city="Stockholm", venueName="Studion, Kulturhuset Stadsteatern"),
    "taket": VenueInfo(city="Stockholm", venueName="Taket, Kulturhuset Stadsteatern"),
    "vitabergsparken": VenueInfo(city="Stockholm", venueName="Vitabergsparken"),
    "vällingby": VenueInfo(city="Vällingby", venueName="Kulturhuset Stadsteatern Vällingby"),
    "parkteatern akalla by": VenueInfo(city="Kista", venueName="Parkteatern Akalla by"),
    "parkteatern bandängens parklek bandhagen": VenueInfo(city="Bandhagen", venueName="Parkteatern Bandängens parklek Bandhagen"),
    "parkteatern farsta torg": VenueInfo(city="Farsta", venueName="Parkteatern Farsta torg"),
    "parkteatern fatbursparken södermalm": VenueInfo(city="Stockholm", venueName="Parkteatern Fatbursparken Södermalm"),
    "parkteatern humlegården östermalm": VenueInfo(city="Stockholm", venueName="Parkteatern Humlegården Östermalm"),
    "parkteatern husby gård": VenueInfo(city="Kista", venueName="Parkteatern Husby gård"),
    "parkteatern husby torg": VenueInfo(city="Kista", venueName="Parkteatern Husby torg"),
    "parkteatern hägerstensåsens amfiteater": VenueInfo(city="Hägersten", venueName="Parkteatern Hägerstensåsens amfiteater"),
    "parkteatern hässelby torg": VenueInfo(city="Hässelby", venueName="Parkteatern Hässelby torg"),
    "parkteatern höglundaparken jordbro": VenueInfo(city="Jordbro", venueName="Parkteatern Höglundaparken Jordbro"),
    "parkteatern kista torg": VenueInfo(city="Kista", venueName="Parkteatern Kista torg"),
    "parkteatern malmparken sollentuna": VenueInfo(city="Sollentuna", venueName="Parkteatern Malmparken Sollentuna"),
    "parkteatern parkleken farstaängen": VenueInfo(city="Farsta", venueName="Parkteatern Parkleken Farstaängen"),
    "parkteatern parkleken gulsippan hässelby": VenueInfo(city="Hässelby", venueName="Parkteatern Parkleken Gulsippan Hässelby"),
    "parkteatern parkleken kristallen solberga": VenueInfo(city="Hägersten", venueName="Parkteatern Parkleken Kristallen Solberga"),
    "parkteatern parkleken lugnet västertorp": VenueInfo(city="Hägersten", venueName="Parkteatern Parkleken Lugnet Västertorp"),
    "parkteatern parkleken rinken rinkeby": VenueInfo(city="Spånga", venueName="Parkteatern Parkleken Rinken Rinkeby"),
    "parkteatern parkleken rågdalen rågsved": VenueInfo(city="Bandhagen", venueName="Parkteatern Parkleken Rågdalen Rågsved"),
    "parkteatern parkleken starrmyran hökarängen": VenueInfo(city="Farsta", venueName="Parkteatern Parkleken Starrmyran Hökarängen"),
    "parkteatern parkleken stråket hässelby": VenueInfo(city="Hässelby", venueName="Parkteatern Parkleken Stråket Hässelby"),
    "parkteatern parkleken vippan fruängen": VenueInfo(city="Hägersten", venueName="Parkteatern Parkleken Vippan Fruängen"),
    "parkteatern parkleken vårgården vårberg": VenueInfo(city="Skärholmen", venueName="Parkteatern Parkleken Vårgården Vårberg"),
    "parkteatern parkleken ådalen vällingby": VenueInfo(city="Vällingby", venueName="Parkteatern Parkleken Ådalen Vällingby"),
    "parkteatern poseidons torg handen": VenueInfo(city="Handen", venueName="Parkteatern Poseidons torg Handen"),
    "parkteatern skarpnäcks torg": VenueInfo(city="Skarpnäck", venueName="Parkteatern Skarpnäcks torg"),
    "parkteatern spånga by parklek": VenueInfo(city="Spånga", venueName="Parkteatern Spånga by parklek"),
    "parkteatern stadshusparken": VenueInfo(city="Stockholm", venueName="Parkteatern Stadshusparken"),
    "parkteatern stamparken östberga": VenueInfo(city="Älvsjö", venueName="Parkteatern Stamparken Östberga"),
    "parkteatern under eken galärparken": VenueInfo(city="Stockholm", venueName="Parkteatern Under Eken Galärparken"),
    "parkteatern ängsholmsparken täby": VenueInfo(city="Täby", venueName="Parkteatern Ängsholmsparken Täby"),
    "parkteatern åkerbyparken täby": VenueInfo(city="Täby", venueName="Parkteatern Åkerbyparken Täby"),
}
